// platform/recon/regulatory-source-coverage.ts
//
// Advisory recon gate: every regulatory instrument with applicabilityStatus
// "direct" or "transposed" must have:
//   - sourceAcquired:true  — the regulator's published binary filed via
//                            `recordRegulatorySource()`;
//   - extracted:true       — a `*-structured.json` exists in the repo (this
//                            is always true for rows in the register, but the
//                            field is kept for completeness / future use);
//   - obligationsLinked>0  — at least one EXPRESSES edge from a Provision
//                            node derived from this document to an Obligation
//                            node in the knowledge graph.
//
// SHIP POSTURE: ENFORCING (Slice 6) — the gate shipped ADVISORY in Slice 5.
// Flipped to enforcing 2026-06-11 once all 16 active sources were acquired.
// sourceAcquired:false → "fail" post-advisoryUntil; obligationsLinked=0 stays
// "warn" (graph EXPRESSES edges are populated incrementally by graph:seed).
//
// Input: reads `Regulations/_source-coverage.json` relative to the monorepo
// root (two levels up from `prototype/`). The file is generated by
// `bun run build:source-coverage`.
//
// Authority: D-REGULATORY-LIBRARY-V1 (CEO-approved 2026-06-11).
// Backing brief: brief:mira:regulatory-library-slice-5-source-coverage-regis:2026-06-11.
// Author: Mira (Compliance / RegTech engineer, engineering).

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import type {
  SourceCoverageReport,
  SourceCoverageRow,
} from "../../scripts/regulatory/build-source-coverage";
import { clock } from "../composition";
import { type ReconResult, type ReconViolation, emptyResult } from "./types";

const PIPELINE = "regulatory-source-coverage";

/**
 * ISO date from which missing regulatory sources become hard failures.
 * Bumped to 2026-06-11 (Slice 6) now that all 16 active sources are acquired.
 * obligationsLinked=0 remains warn (EXPRESSES edges populated by graph:seed).
 */
export const ADVISORY_UNTIL = "2026-06-11";

/** Injected deps for testing (bypass filesystem). */
export interface SourceCoverageDeps {
  /** Override the rows to check (tests inject mock data). */
  readonly rows?: readonly SourceCoverageRow[];
  /** Override advisory boundary (tests). Default `ADVISORY_UNTIL`. */
  readonly advisoryUntil?: string;
  /** Override "now" (tests). Default `clock.now()`. */
  readonly asOfDate?: string;
}

function defaultReportPath(): string {
  // import.meta.dir = <worktree>/prototype/platform/recon
  // Walk up: recon → platform → prototype → repo root
  return resolve(import.meta.dir, "..", "..", "..", "Regulations", "_source-coverage.json");
}

function loadRowsFromDisk(): SourceCoverageRow[] {
  const reportPath = defaultReportPath();
  if (!existsSync(reportPath)) {
    // Report not yet generated — treat as zero rows (advisory; CI is green
    // on a clean checkout before `build:source-coverage` has been run).
    return [];
  }
  try {
    const raw = readFileSync(reportPath, "utf-8");
    const report = JSON.parse(raw) as SourceCoverageReport;
    return report.rows ?? [];
  } catch {
    return [];
  }
}

export function run(deps: SourceCoverageDeps = {}): ReconResult & {
  active: number;
  acquired: number;
  extracted: number;
  fullyLinked: number;
  advisoryUntil: string;
} {
  const result = emptyResult(PIPELINE);
  const violations: ReconViolation[] = [];

  const advisoryUntil = deps.advisoryUntil ?? ADVISORY_UNTIL;
  const asOfDate = (deps.asOfDate ?? clock.now()).slice(0, 10);

  // Post-advisory: missing sources are hard failures; obligations-not-linked stays warn.
  const postAdvisory = asOfDate >= advisoryUntil;

  const rows = deps.rows !== undefined ? deps.rows : loadRowsFromDisk();

  let active = 0;
  let acquired = 0;
  let extracted = 0;
  let fullyLinked = 0;

  for (const row of rows) {
    const inScope =
      row.applicabilityStatus === "direct" || row.applicabilityStatus === "transposed";
    if (!inScope) continue;

    active++;
    result.asserted += 3; // three assertions per in-scope instrument

    if (row.sourceAcquired) acquired++;
    if (row.extracted) extracted++;
    if (row.sourceAcquired && row.extracted && row.obligationsLinked > 0) fullyLinked++;

    const subject = `${row.slug} (${row.applicabilityStatus})`;

    if (!row.sourceAcquired) {
      violations.push({
        subject,
        message: `Instrument \`${row.slug}\` (${row.applicabilityStatus}) has no filed regulatory source. Remediation: \`BANK_EVENT_DB="$HOME/.local/share/bank/event.db" bun run acquire:source --instrument-id <ID> --slug ${row.slug} --title "${row.title}" --regulator "${row.regulator ?? ""}" --from <path-to-pdf>\`. Citation: D-REGULATORY-LIBRARY-V1.`,
        severity: postAdvisory ? "fail" : "warn",
      });
    }

    if (!row.extracted) {
      violations.push({
        subject,
        message: `Instrument \`${row.slug}\` (${row.applicabilityStatus}) has no structured JSON (\`extracted:false\`). Remediation: run extraction pipeline for this slug. Citation: D-REGULATORY-LIBRARY-V1.`,
        severity: postAdvisory ? "fail" : "warn",
      });
    }

    if (row.obligationsLinked === 0) {
      violations.push({
        subject,
        message: `Instrument \`${row.slug}\` (${row.applicabilityStatus}) has 0 EXPRESSES edges (no obligations linked). Remediation: re-seed the graph (\`bun run graph:seed\`) and verify obligation extraction. Citation: D-REGULATORY-LIBRARY-V1, Principle 2.`,
        // stays warn — EXPRESSES edges are populated incrementally; not gated on source-filing
        severity: "warn",
      });
    }
  }

  result.violations = violations;
  // Advisory mode: ok=true regardless of warn violations (only "fail" flips ok)
  result.ok = violations.every((v) => v.severity !== "fail");

  return {
    ...result,
    active,
    acquired,
    extracted,
    fullyLinked,
    advisoryUntil,
  };
}

if (import.meta.main) {
  const r = run();
  console.log(
    JSON.stringify({
      level: r.ok ? "info" : "error",
      time: r.asOf,
      service: "bank-prototype",
      pipeline: r.pipeline,
      asserted: r.asserted,
      violations: r.violations.length,
      active: r.active,
      acquired: r.acquired,
      extracted: r.extracted,
      fullyLinked: r.fullyLinked,
      advisoryUntil: r.advisoryUntil,
      ok: r.ok,
      msg: r.ok
        ? `regulatory-source-coverage advisory: ${r.active} in-scope instruments, ${r.acquired} acquired, ${r.fullyLinked} fully-linked`
        : "regulatory-source-coverage FAILED",
      detail: r.violations.slice(0, 40),
    }),
  );
  if (!r.ok) process.exit(1);
}
