// scripts/migrate/rescue-dangling-recordfiled-blobs.test.ts
//
// The HARD-RULE contract: a blob is re-put ONLY when the regenerated bytes
// hash EXACTLY to the recorded `documentHash`. PR-reference synthetic stubs
// regenerate from (runId, prRef, briefId, agentName); a hash mismatch (e.g.
// a tampered template or wrong join) is SKIPPED, never written — otherwise
// the content-addressed store would be corrupted.
//
// Author: Vera (Internal audit engineer, third line)

import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { hashContent } from "../../platform/document-store/hash";
import { LocalFsDocumentStore } from "../../platform/document-store/local-fs";
import type { DocumentHash } from "../../platform/document-store/types";
import { makeRecordFiled } from "../../platform/event-store/event-types";
import type { Event } from "../../platform/event-store/types";
import { runRescue } from "./rescue-dangling-recordfiled-blobs";

let storeRoot: string;
let store: LocalFsDocumentStore;

beforeEach(() => {
  storeRoot = mkdtempSync(join(tmpdir(), "rescue-store-"));
  store = new LocalFsDocumentStore({ root: storeRoot });
});

afterEach(() => {
  rmSync(storeRoot, { recursive: true, force: true });
});

const RUN_ID = "atlas:2026-05-26T08-16-45-354Z";
const PR_REF = "https://github.com/marchouze/scrooge/pull/810";
const BRIEF_ID = "brief:atlas:some-work:2026-05-26";
const AGENT_NAME = "Atlas";

/** Reproduce the close-run synthetic PR-stub body verbatim. */
function stubBody(runId: string, prRef: string, briefId: string, agentName: string): string {
  return `# Code PR Deliverable\n\nThis record references a code pull request delivered as part of agent run ${runId}.\n\nPR: ${prRef}\nBrief: ${briefId}\nAgent: ${agentName}\n`;
}

function prStubRecordFiled(documentHash: string, asOf: string): Event {
  return makeRecordFiled({
    asOf,
    entity: "LE-ZA-HOZ-BANK",
    actor: { type: "service", id: "agent:atlas" },
    citations: ["D-RMS-PHASE-1"],
    payload: {
      recordId: `record:${RUN_ID}:0:pr-https-github-com-marchouze-scrooge-pull-810`,
      registerKey: "documents",
      documentHash,
      classification: "agent-internal",
      retention: { citationRef: "D-RMS-PHASE-1", minimumYears: 5, archivalTier: "cool" },
      metadata: { title: "x", path: PR_REF, category: "documents", prRef: PR_REF },
    },
  });
}

function runCompleted(asOf: string): Event {
  return {
    event_id: "evt-run-completed-1",
    type: "AgentRunCompleted",
    as_of: asOf,
    entity: "LE-ZA-HOZ-BANK",
    actor: { type: "service", id: "agent:atlas" },
    citations: ["D-RMS-PHASE-1"],
    payload: {
      runId: RUN_ID,
      briefId: BRIEF_ID,
      agent: { name: AGENT_NAME, position: "Core banking platform architect" },
      deliverableDocumentHashes: [],
    },
  } as Event;
}

describe("rescue-dangling-recordfiled-blobs — hash-exact contract", () => {
  it("rescues a PR-stub whose regenerated body hashes to the recorded hash", () => {
    const correctHash = hashContent(
      new TextEncoder().encode(stubBody(RUN_ID, PR_REF, BRIEF_ID, AGENT_NAME)),
      "blake3",
    );
    const asOf = "2026-06-12T10:00:00.000Z"; // post-enforcement → fail tier

    expect(store.exists(correctHash as DocumentHash)).toBe(false);

    const summary = runRescue({
      recordFiledEvents: [prStubRecordFiled(correctHash, asOf)],
      runCompletedEvents: [runCompleted(asOf)],
      store,
    });

    expect(summary.rescued).toBe(1);
    expect(summary.rescuedPrStub).toBe(1);
    expect(summary.failsRemaining).toBe(0);
    // The byte-exact blob now resolves in the store.
    expect(store.exists(correctHash as DocumentHash)).toBe(true);
  });

  it("NEVER writes when the recorded hash does not match the regenerated body (HARD RULE)", () => {
    // A bogus recorded hash the synthetic body will never produce.
    const bogusHash = `blake3:${"cd".repeat(32)}`;
    const asOf = "2026-06-12T10:00:00.000Z";

    const summary = runRescue({
      recordFiledEvents: [prStubRecordFiled(bogusHash, asOf)],
      runCompletedEvents: [runCompleted(asOf)],
      store,
    });

    expect(summary.rescued).toBe(0);
    expect(summary.irreducible.hashMismatch).toBe(1);
    expect(summary.failsRemaining).toBe(1);
    // The store was NOT written under the bogus hash — content-addressed
    // integrity preserved (no fabricated bytes under an existing hash).
    expect(store.exists(bogusHash as DocumentHash)).toBe(false);
  });

  it("reports noRunInfo when the AgentRunCompleted join fails (no fabrication)", () => {
    const correctHash = hashContent(
      new TextEncoder().encode(stubBody(RUN_ID, PR_REF, BRIEF_ID, AGENT_NAME)),
      "blake3",
    );
    const asOf = "2026-06-12T10:00:00.000Z";

    const summary = runRescue({
      recordFiledEvents: [prStubRecordFiled(correctHash, asOf)],
      runCompletedEvents: [], // no run info to join
      store,
    });

    expect(summary.rescued).toBe(0);
    expect(summary.irreducible.noRunInfo).toBe(1);
    expect(store.exists(correctHash as DocumentHash)).toBe(false);
  });

  it("classifies a non-regenerable category as irreducible, never writes", () => {
    const hash = `blake3:${"ef".repeat(32)}`;
    const asOf = "2026-06-12T10:00:00.000Z";
    const perfFeedback = makeRecordFiled({
      asOf,
      entity: "LE-ZA-HOZ-BANK",
      actor: { type: "service", id: "agent:sade" },
      citations: ["D-RMS-PHASE-1"],
      payload: {
        recordId: "perf-feedback:ravi:2026-05-27",
        registerKey: "documents",
        documentHash: hash,
        classification: "governance-seat",
        retention: { citationRef: "D-RMS-PHASE-1", minimumYears: 5, archivalTier: "cool" },
        metadata: { title: "x", path: "rms://performance/...", category: "Performance feedback" },
      },
    });

    const summary = runRescue({
      recordFiledEvents: [perfFeedback],
      runCompletedEvents: [],
      store,
    });

    expect(summary.rescued).toBe(0);
    expect(summary.irreducible.notRegenerable).toBe(1);
    expect(summary.failsRemaining).toBe(1);
    expect(store.exists(hash as DocumentHash)).toBe(false);
  });

  it("is idempotent: a blob already present is counted alreadyPresent, not re-rescued", () => {
    const body = stubBody(RUN_ID, PR_REF, BRIEF_ID, AGENT_NAME);
    const correctHash = hashContent(new TextEncoder().encode(body), "blake3");
    const asOf = "2026-06-12T10:00:00.000Z";
    store.put(body); // pre-seed the blob

    const summary = runRescue({
      recordFiledEvents: [prStubRecordFiled(correctHash, asOf)],
      runCompletedEvents: [runCompleted(asOf)],
      store,
    });

    expect(summary.rescued).toBe(0);
    expect(summary.alreadyPresent).toBe(1);
    expect(summary.danglingTotal).toBe(0);
  });
});
