// scripts/migrate/rescue-dangling-recordfiled-blobs.ts
//
// Idempotent, re-runnable rescue of DANGLING `RecordFiled` blobs in the
// read-path (shared/home) document store — the genuinely-recoverable
// subset of the census surfaced by `recon:rms-document-blob-integrity`.
//
// THE PROBLEM. `recon:rms-document-blob-integrity` reports `RecordFiled`
// events whose `documentHash` has no blob in the read-path document store.
// Against the live shared-home pair
// (`BANK_EVENT_DB=$HOME/.local/share/bank/event.db`,
// `BANK_DOCUMENT_STORE` unset → `$HOME/.local/share/bank/documents`) the
// gate reports ~1,867 dangling records. They are NOT recoverable by
// `migrate:document-store-blobs` — the in-repo `data/documents` is empty
// and the per-worktree stores that once held the bytes are pruned. The
// blobs are gone; only a deterministic REGENERATION of the original bytes
// can rescue a record, and only when the regenerated bytes hash to the
// RECORDED `documentHash`.
//
// THE HARD RULE (content-addressed integrity is sacred — Engineering
// Charter; D-RMS-PHASE-3; Principle 1). A blob is re-put under a hash ONLY
// when the regenerated bytes hash EXACTLY to the recorded `documentHash`.
// We NEVER fabricate different content under an existing hash — that would
// corrupt the content-addressed store (a reader trusts that the bytes at
// `blake3:H` hash to `H`). Every candidate is hash-checked; a mismatch is
// reported as `hashMismatch` and SKIPPED, never written.
//
// WHAT IS REGENERABLE (the only two deterministic sources we trust):
//
//   1. AGENT-RUN PR-REFERENCE STUBS (`record:<runId>:<i>:pr-...`). When an
//      agent run delivered a code PR rather than a local markdown file,
//      `close-run` stored a SYNTHETIC markdown body built from a fixed
//      template over `(runId, prRef, briefId, agentName)`. All four are
//      recoverable: `runId` from the recordId, `prRef` from the
//      `RecordFiled` metadata, and `briefId` + `agentName` by joining to
//      the run's `AgentRunCompleted` event. The template is reproduced
//      VERBATIM here (kept in lock-step with `close-run.ts` — see the
//      comment on `prStubBody`). Each regeneration is hash-checked.
//
//   2. BYTE-STABLE IN-REPO REGULATORY SOURCES (`reg-source:...`). When the
//      `metadata.path` still resolves to an in-repo source file whose bytes
//      are unchanged since filing, re-reading and re-putting reproduces the
//      exact recorded hash. (Most reg-source paths point at ephemeral
//      `/tmp/...` extraction dirs or in-repo `*-structured.json` files that
//      have since been re-extracted — those fail the hash check and are
//      correctly skipped, NOT rescued.)
//
// Everything else (perf-feedback, bespoke decision/document/owner-inbox
// markdown renders, RAVI stress notes, NPA docs, reg excerpts) embedded a
// freshly-generated event id and/or folded the event log as it stood at
// filing time, so it is NOT deterministically reproducible — those records
// stay dangling and are reported as the irreducible loss. We do NOT guess.
//
// STORE RESOLUTION. The rescue writes to the SAME read-path store the gate
// audits and the dashboard reads: `resolveDocumentStoreRoot({})` (the
// home-default-ENABLED resolution). In the live sweep that is
// `$HOME/.local/share/bank/documents`; under the CI/local pin it is the
// repo-local `BANK_DOCUMENT_STORE`. This is exactly the store
// `rms-document-blob-integrity`'s primary tier resolves to, so a rescued
// blob immediately turns its record green.
//
// IDEMPOTENT + RE-RUNNABLE. A blob already present at its hash is skipped
// (`alreadyPresent`). The document-store `put` is content-addressed and
// itself idempotent. Re-running copies nothing already rescued. The event
// log is NEVER mutated — this is a blob-only backfill (no new RecordFiled
// events; the canonical records already exist — Principle 1).
//
// Exit code: 0 always (rescue is best-effort over a known-lossy estate;
// the AUTHORITATIVE pass/fail signal is `recon:rms-document-blob-integrity`
// itself, which stays enforcing). The summary JSON on stdout carries the
// rescued count and the irreducible-loss breakdown.
//
// Authority: D-RMS-PHASE-3 (RecordFiled is the canonical deliverable
//            event); D-CROSS-WORKTREE-EVENT-STORE-SYNC (read-path store
//            resolution precedent); Engineering Charter (content-addressed
//            integrity; no green by concealment — we rescue what is
//            byte-exact and report the rest honestly, never allowlist).
//            Seed precedent: Vera (Internal audit engineer, third line)'s
//            PR #1194 hand-rescue of blob `blake3:8cb3a86e…`.
// Author: Vera (Internal audit engineer, third line)

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { eventStore } from "../../platform/composition";
import { hashContent } from "../../platform/document-store/hash";
import { LocalFsDocumentStore } from "../../platform/document-store/local-fs";
import {
  inRepoDocumentStoreRoot,
  resolveDocumentStoreRoot,
} from "../../platform/document-store/resolve-document-store";
import type { DocumentHash } from "../../platform/document-store/types";
import type { Event } from "../../platform/event-store/types";

const ENFORCEMENT_DATE = "2026-06-11";

/**
 * VERBATIM copy of the PR-reference synthetic body in
 * `scripts/dispatch/close-run.ts` (the `prRefs` loop). If close-run's
 * template ever changes, historical hashes will not regenerate — that is
 * correct: only records filed under the matching template are rescued, and
 * the hash check is the guard. Kept here (not imported) because close-run
 * builds it inline inside `main()` and is not exported; the duplication is
 * intentional and asserted by the rescue's own hash-exact contract.
 */
function prStubBody(runId: string, prRef: string, briefId: string, agentName: string): string {
  return `# Code PR Deliverable\n\nThis record references a code pull request delivered as part of agent run ${runId}.\n\nPR: ${prRef}\nBrief: ${briefId}\nAgent: ${agentName}\n`;
}

export interface RescueSummary {
  danglingTotal: number;
  rescued: number;
  rescuedPrStub: number;
  rescuedRegSource: number;
  alreadyPresent: number;
  /** Records that remain dangling, by reason. */
  irreducible: {
    notRegenerable: number; // category has no deterministic source
    hashMismatch: number; // regenerated/file bytes did not match recorded hash
    sourceMissing: number; // in-repo source file gone (reg-source)
    noRunInfo: number; // PR stub but AgentRunCompleted join failed
  };
  /** Post-cutoff fails still dangling after rescue (these gate the live run). */
  failsRemaining: number;
  warnsRemaining: number;
}

export interface RescueDeps {
  readonly recordFiledEvents?: readonly Event[];
  readonly runCompletedEvents?: readonly Event[];
  /** Destination read-path store. Default: home-default-enabled resolution. */
  readonly store?: LocalFsDocumentStore;
  /** Repo root for resolving in-repo reg-source paths. Default: walk from this module. */
  readonly repoRoot?: string;
  /** When true, do not write — just classify (census/dry-run). */
  readonly dryRun?: boolean;
}

function readPathStore(): LocalFsDocumentStore {
  return new LocalFsDocumentStore({ root: resolveDocumentStoreRoot({}).root });
}

/** Join map: runId → {briefId, agentName} from AgentRunCompleted. */
function buildRunInfo(
  events: Iterable<Event>,
): Map<string, { briefId: string; agentName: string }> {
  const m = new Map<string, { briefId: string; agentName: string }>();
  for (const e of events) {
    const p = e.payload as Record<string, unknown>;
    const runId = typeof p.runId === "string" ? p.runId : null;
    if (!runId) continue;
    const briefId = typeof p.briefId === "string" ? p.briefId : "";
    const agent = p.agent as { name?: unknown } | undefined;
    const agentName = typeof agent?.name === "string" ? agent.name : "";
    m.set(runId, { briefId, agentName });
  }
  return m;
}

export function runRescue(deps: RescueDeps = {}): RescueSummary {
  const store = deps.store ?? readPathStore();
  const repoRoot = deps.repoRoot ?? resolve(inRepoDocumentStoreRoot(), "..", "..", "..");

  const recordEvents: Iterable<Event> =
    deps.recordFiledEvents ?? eventStore.replay({ type: "RecordFiled" });
  const runEvents: Iterable<Event> =
    deps.runCompletedEvents ?? eventStore.replay({ type: "AgentRunCompleted" });

  const runInfo = buildRunInfo(runEvents);

  const summary: RescueSummary = {
    danglingTotal: 0,
    rescued: 0,
    rescuedPrStub: 0,
    rescuedRegSource: 0,
    alreadyPresent: 0,
    irreducible: { notRegenerable: 0, hashMismatch: 0, sourceMissing: 0, noRunInfo: 0 },
    failsRemaining: 0,
    warnsRemaining: 0,
  };

  for (const e of recordEvents) {
    const p = e.payload as Record<string, unknown>;
    const hash = typeof p.documentHash === "string" ? (p.documentHash as DocumentHash) : null;
    if (!hash) continue;

    if (store.exists(hash)) {
      summary.alreadyPresent++;
      continue;
    }

    summary.danglingTotal++;
    const recordId = typeof p.recordId === "string" ? p.recordId : "";
    const meta = (p.metadata ?? {}) as Record<string, unknown>;
    const eventDate = (e.as_of ?? "").slice(0, 10);
    const isFail = eventDate >= ENFORCEMENT_DATE;

    let rescued = false;

    // Strategy 1 — PR-reference synthetic stub.
    const prRef = typeof meta.prRef === "string" ? meta.prRef : null;
    const stubMatch = recordId.match(/^record:(.+):(\d+):pr-/);
    if (prRef && stubMatch) {
      const runId = stubMatch[1] ?? "";
      const info = runInfo.get(runId);
      if (!info) {
        summary.irreducible.noRunInfo++;
      } else {
        const body = prStubBody(runId, prRef, info.briefId, info.agentName);
        const regen = hashContent(new TextEncoder().encode(body), "blake3");
        if (regen === hash) {
          if (!deps.dryRun) {
            const put = store.put(body);
            // Defence-in-depth: the put hashes the bytes itself; assert the
            // store landed them at the recorded hash before counting.
            if (put.hash !== hash) {
              throw new Error(
                `rescue invariant violated: put.hash ${put.hash} !== recorded ${hash} for ${recordId}`,
              );
            }
          }
          summary.rescued++;
          summary.rescuedPrStub++;
          rescued = true;
        } else {
          summary.irreducible.hashMismatch++;
        }
      }
    } else if (recordId.startsWith("reg-source:")) {
      // Strategy 2 — byte-stable in-repo regulatory source file.
      const path = typeof meta.path === "string" ? meta.path : null;
      const candidate = resolveInRepoSource(repoRoot, path);
      if (!candidate) {
        summary.irreducible.sourceMissing++;
      } else {
        const bytes = new Uint8Array(readFileSync(candidate));
        const regen = hashContent(bytes, "blake3");
        if (regen === hash) {
          if (!deps.dryRun) {
            const put = store.put(bytes);
            if (put.hash !== hash) {
              throw new Error(
                `rescue invariant violated: put.hash ${put.hash} !== recorded ${hash} for ${recordId}`,
              );
            }
          }
          summary.rescued++;
          summary.rescuedRegSource++;
          rescued = true;
        } else {
          summary.irreducible.hashMismatch++;
        }
      }
    } else {
      // No deterministic regeneration source for this category.
      summary.irreducible.notRegenerable++;
    }

    if (!rescued) {
      if (isFail) summary.failsRemaining++;
      else summary.warnsRemaining++;
    }
  }

  return summary;
}

/** Try the candidate roots for an in-repo reg-source path; null if none exists. */
function resolveInRepoSource(repoRoot: string, path: string | null): string | null {
  if (!path) return null;
  // Absolute ephemeral paths (/tmp/..., ~/Desktop/...) are gone — never rescuable.
  if (path.startsWith("/") || path.startsWith("~")) return null;
  const norm = path.replace(/^(\.\.\/)+/, "");
  const tries = [
    resolve(repoRoot, path),
    resolve(repoRoot, norm),
    resolve(repoRoot, "prototype", norm),
  ];
  for (const t of tries) if (existsSync(t)) return t;
  return null;
}

if (import.meta.main) {
  const dryRun = process.argv.includes("--dry-run");
  const summary = runRescue({ dryRun });
  console.log(
    JSON.stringify(
      {
        level: "info",
        service: "bank-prototype",
        script: "rescue-dangling-recordfiled-blobs",
        dryRun,
        msg: dryRun
          ? "RecordFiled blob-rescue DRY RUN (no writes)"
          : "RecordFiled blob-rescue complete",
        summary,
      },
      null,
      2,
    ),
  );
}
