// v2-core/control-plane/envelope.ts
//
// V2Envelope — the v2 event envelope (V2 S2).
//
// Every event emitted in the v2 code-line is wrapped in a `V2Envelope`. S2
// adds the `tenantId` axis as a REQUIRED field (no optionals — an unknown
// tenant is a rejected event, not a defaulted one; the factory defaults to the
// anchor tenant when the caller omits the argument, making the common case
// ergonomic without hiding the field).
//
// SCOPE (S2 = dark, not enforced)
// --------------------------------
// The envelope type and factory are available; no live bus handler, routing
// gate, or control-plane store reads this field yet. Enforcement and isolation
// land in S3+. Call-sites written against `createV2Envelope` today are
// future-proof — the S3 routing gate only needs to enable itself, not retrofit
// envelope construction.
//
// Authority: D-V2-TENANCY-ARCHITECTURE; D-V2-BBAAS-BLUEPRINT-SYNTHESIS.
// Author: Atlas (Core banking platform architect, engineering).

import { z } from "zod";
import type { Instant } from "../fil-core/primitives";
import { V2_ENVELOPE_SCHEMA_VERSION } from "./schema-version";
import { ANCHOR_TENANT_ID, type TenantId, tenantIdSchema } from "./tenant";

// ---------------------------------------------------------------------------
// V2Envelope
// ---------------------------------------------------------------------------

/**
 * The v2 event envelope. Every event emitted in the v2 code-line carries this
 * wrapper. Fields:
 *
 * - `tenantId`      — the tenant that owns this event (REQUIRED; defaults to the
 *                     anchor tenant via `createV2Envelope`).
 * - `schemaVersion` — the EXPLICIT payload schema version (REQUIRED; defaults to
 *                     `V2_ENVELOPE_SCHEMA_VERSION` via `createV2Envelope`).
 *                     V2 stops inferring version from incidental payload shape;
 *                     this field is the queryable discriminator and the input to
 *                     version-explicit upcaster dispatch
 *                     (D-EVENT-ENVELOPE-SCHEMA-VERSION).
 * - `eventId`       — a unique identifier for this event instance (caller-
 *                     supplied or generated by `createV2Envelope`).
 * - `issuedAt`      — the wall-clock instant the envelope was created.
 * - `payload`       — the typed event payload (generic; the caller constrains it).
 *
 * Downstream slices (S3+) may add: `correlationId`, `causationId`, and routing
 * metadata. Those additions are backwards-compatible minor extensions — the
 * `tenantId` and `schemaVersion` fields established here are the anchors.
 */
export interface V2Envelope<TPayload = unknown> {
  readonly tenantId: TenantId;
  readonly schemaVersion: number;
  readonly eventId: string;
  readonly issuedAt: Instant;
  readonly payload: TPayload;
}

export const v2EnvelopeSchema = z.object({
  tenantId: tenantIdSchema,
  schemaVersion: z.number().int().positive(),
  eventId: z.string().min(1),
  issuedAt: z.custom<Instant>(),
  payload: z.unknown(),
});

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * The base fields a caller supplies to `createV2Envelope`. `eventId`,
 * `issuedAt`, and `payload` are required; `schemaVersion` is optional and
 * defaults to `V2_ENVELOPE_SCHEMA_VERSION` (the go-forward version) so the
 * common case stays ergonomic while the field is REQUIRED on the envelope type.
 */
export interface V2EnvelopeBase<TPayload = unknown> {
  readonly eventId: string;
  readonly issuedAt: Instant;
  readonly payload: TPayload;
  /** Explicit schema version; defaults to `V2_ENVELOPE_SCHEMA_VERSION`. */
  readonly schemaVersion?: number;
}

/**
 * Create a `V2Envelope` from base fields.
 *
 * `tenantId` defaults to `ANCHOR_TENANT_ID` and `schemaVersion` to
 * `V2_ENVELOPE_SCHEMA_VERSION` when omitted — making the common (anchor-tenant,
 * current-version) case ergonomic while keeping BOTH fields REQUIRED on the
 * envelope type itself. The defaults are intentionally explicit: callers know
 * they can specify a different tenant / version, and the routing + upcaster
 * layers can assert every envelope has a non-null tenant and an explicit
 * version without conditional logic.
 *
 * @param base     - the event fields (eventId, issuedAt, payload, [schemaVersion])
 * @param tenantId - the owning tenant; defaults to ANCHOR_TENANT_ID
 */
export function createV2Envelope<TPayload>(
  base: V2EnvelopeBase<TPayload>,
  tenantId: TenantId = ANCHOR_TENANT_ID as TenantId,
): V2Envelope<TPayload> {
  return {
    tenantId,
    schemaVersion: base.schemaVersion ?? V2_ENVELOPE_SCHEMA_VERSION,
    eventId: base.eventId,
    issuedAt: base.issuedAt,
    payload: base.payload,
  };
}
