// v2-core/control-plane/envelope.ts
//
// V2Envelope — the v2 event envelope (V2 S2).
//
// Every event emitted in the v2 code-line is wrapped in a `V2Envelope`. S2
// adds the `tenantId` axis as a REQUIRED field (no optionals — an unknown
// tenant is a rejected event, not a defaulted one; the factory defaults to the
// anchor tenant when the caller omits the argument, making the common case
// ergonomic without hiding the field).
//
// SCOPE (S2 = dark, not enforced)
// --------------------------------
// The envelope type and factory are available; no live bus handler, routing
// gate, or control-plane store reads this field yet. Enforcement and isolation
// land in S3+. Call-sites written against `createV2Envelope` today are
// future-proof — the S3 routing gate only needs to enable itself, not retrofit
// envelope construction.
//
// Authority: D-V2-TENANCY-ARCHITECTURE; D-V2-BBAAS-BLUEPRINT-SYNTHESIS.
// Author: Atlas (Core banking platform architect, engineering).

import { z } from "zod";
import type { Instant } from "../fil-core/primitives";
import { ANCHOR_TENANT_ID, type TenantId, tenantIdSchema } from "./tenant";

// ---------------------------------------------------------------------------
// V2Envelope
// ---------------------------------------------------------------------------

/**
 * The current default schema version stamped on every freshly-constructed
 * `V2Envelope`. The 10 existing v2-parallel footholds were authored before
 * the field existed; they read as `schemaVersion 1` (see
 * `V2_ENVELOPE_SCHEMA_VERSION_DEFAULT` consumers + the control-plane store's
 * append-time backfill). A future payload-shape change for a given event type
 * bumps its schema version and the upcaster reads the older value to migrate.
 *
 * Authority: D-EVENT-ENVELOPE-SCHEMA-VERSION.
 */
export const V2_ENVELOPE_SCHEMA_VERSION_DEFAULT = 1 as const;

/**
 * The v2 event envelope. Every event emitted in the v2 code-line carries this
 * wrapper. Fields:
 *
 * - `tenantId`      — the tenant that owns this event (REQUIRED; defaults to the
 *                     anchor tenant via `createV2Envelope`).
 * - `schemaVersion` — the envelope/payload schema version for this event
 *                     (REQUIRED; defaults to `V2_ENVELOPE_SCHEMA_VERSION_DEFAULT`
 *                     = 1 via `createV2Envelope`). A monotonically-increasing
 *                     integer; an upcaster keyed on `(type, schemaVersion)`
 *                     migrates older payloads forward on read. Aligns with the
 *                     v1 event-store's per-event schema-version discipline.
 * - `eventId`       — a unique identifier for this event instance (caller-
 *                     supplied or generated by `createV2Envelope`).
 * - `issuedAt`      — the wall-clock instant the envelope was created.
 * - `payload`       — the typed event payload (generic; the caller constrains it).
 *
 * Downstream slices (S3+) will add: `correlationId`, `causationId`, and routing
 * metadata. Those additions are backwards-compatible minor extensions — the
 * `tenantId` field (S2) and `schemaVersion` field (W0) established here are the
 * anchors. Authority: D-EVENT-ENVELOPE-SCHEMA-VERSION;
 * D-EVENT-ENVELOPE-TENANT-COLUMN.
 */
export interface V2Envelope<TPayload = unknown> {
  readonly tenantId: TenantId;
  readonly schemaVersion: number;
  readonly eventId: string;
  readonly issuedAt: Instant;
  readonly payload: TPayload;
}

export const v2EnvelopeSchema = z.object({
  tenantId: tenantIdSchema,
  schemaVersion: z.number().int().positive(),
  eventId: z.string().min(1),
  issuedAt: z.custom<Instant>(),
  payload: z.unknown(),
});

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * The base fields a caller supplies to `createV2Envelope`. `tenantId` and
 * `schemaVersion` are NOT part of the base shape — the factory supplies them
 * (the former defaults to `ANCHOR_TENANT_ID`, the latter to
 * `V2_ENVELOPE_SCHEMA_VERSION_DEFAULT`) so existing v1 event origins can wrap
 * without specifying either in the common case. A caller bumping a payload
 * shape passes an explicit `schemaVersion` via the factory options.
 */
export interface V2EnvelopeBase<TPayload = unknown> {
  readonly eventId: string;
  readonly issuedAt: Instant;
  readonly payload: TPayload;
}

/**
 * Optional factory overrides. Both default when omitted:
 *   - `tenantId`      → `ANCHOR_TENANT_ID`
 *   - `schemaVersion` → `V2_ENVELOPE_SCHEMA_VERSION_DEFAULT` (= 1)
 */
export interface V2EnvelopeOptions {
  readonly tenantId?: TenantId;
  readonly schemaVersion?: number;
}

/**
 * Create a `V2Envelope` from base fields.
 *
 * `tenantId` defaults to `ANCHOR_TENANT_ID` and `schemaVersion` to
 * `V2_ENVELOPE_SCHEMA_VERSION_DEFAULT` (= 1) when omitted — making the common
 * (anchor-tenant, current-schema) case ergonomic while keeping both fields
 * REQUIRED on the envelope type itself. The defaults are intentionally
 * explicit: callers know they can override either, and downstream layers can
 * assert every envelope has a non-null tenant and a positive schema version
 * without conditional logic.
 *
 * BACK-COMPAT: the prior signature accepted a bare `tenantId` positional
 * argument. That positional form is still accepted (a `TenantId` string), so
 * the 10 existing v2-parallel footholds calling `createV2Envelope(base, tid)`
 * compile unchanged and read as `schemaVersion 1`.
 *
 * @param base    - the event fields (eventId, issuedAt, payload)
 * @param options - tenantId / schemaVersion overrides, OR a bare TenantId
 *                  (back-compat positional form)
 */
export function createV2Envelope<TPayload>(
  base: V2EnvelopeBase<TPayload>,
  options: V2EnvelopeOptions | TenantId = {},
): V2Envelope<TPayload> {
  const opts: V2EnvelopeOptions =
    typeof options === "string" ? { tenantId: options as TenantId } : options;
  return {
    tenantId: opts.tenantId ?? (ANCHOR_TENANT_ID as TenantId),
    schemaVersion: opts.schemaVersion ?? V2_ENVELOPE_SCHEMA_VERSION_DEFAULT,
    eventId: base.eventId,
    issuedAt: base.issuedAt,
    payload: base.payload,
  };
}
