// prototype/scripts/record-camille-cfo-decisions.ts
//
// Operationalise Camille (CFO)'s first own-authority Decision event.
// Authority: brief:atlas:gateway-scenario-d-cfo-coo-cco-authority-operati:2026-05-18
//
// Run once from prototype/: bun run scripts/record-camille-cfo-decisions.ts
// This script stays in the repo as an audit record.

import { clock } from "../platform/composition";
import { recordDecision } from "../runtime/decisions/record";

recordDecision(
  {
    decisionId: "D-CFO-BA-RETURNS-SIGN-OFF-2026-Q2",
    phase: "approved",
    authority: "CFO",
    authorityRef: "camille@bank",
    title: "CFO sign-off: Q2 2026 build-phase BA return suite — no material findings",
    category: "finance",
    recommendation:
      "Sign off the Q2 2026 BA return suite (BA 110, BA 100, BA 350, BA 600) as generated by the reporting substrate. Capital ratios comply with Reg 38(2); LCR within limits; no material exceptions noted.",
    rationale:
      "BA returns generated and reviewed under CFO mandate per Camille operating spec §9. Reg 38(2) all-in CET1 minimum is 7%; scenario shows 10%. LCR exceeds 100% threshold. No material exceptions. Next sign-off at Q3 2026 period close.",
    sourceDocHashes: [],
    citations: ["BANKS-ACT-94-1990-REG38", "BA-RETURNS-SUITE-2026-Q2"],
    recordedVia: "agent:autonomous",
  },
  clock.now(),
);
