// platform/event-store/event-types/decision-request.ts
//
// AgentDecisionRequired event-payload schema.
//
// Emitted when an agent needs a human or higher-authority agent to make
// a decision before proceeding. Distinct from AgentEscalation (which is
// a severity-graded escalation channel with an acknowledge/decide/delegate
// lifecycle) — AgentDecisionRequired is a lightweight request-for-input
// that blocks forward progress until a response lands.
//
// Authority: Principle 6 — autonomous by default; humans oversee the
// residual. Every step an agent cannot authorise on its own is a formal
// typed channel (not a chat side-channel).
//
// See also: platform/event-trigger/ — dispatch/subscribe library that
// emits and consumes this event type.
//
// Author: Atlas (Core banking platform architect, engineering)

import { z } from "zod";

import { newEventId } from "../../core/types";
import { type Actor, type Event, eventSchema } from "../types";

// ---------------------------------------------------------------------------
// AgentDecisionRequired
// ---------------------------------------------------------------------------

export const agentDecisionRequiredPayloadSchema = z.object({
  /**
   * Unique request identifier — e.g. "DR-ATLAS-20260515-A1B2".
   * Generated by the dispatching agent; unique within the bank entity.
   */
  requestId: z.string().min(1),

  /**
   * Agent name or URN that is raising the request — e.g. "atlas" or
   * "agent:atlas". Matches AgentRegistered.agentId convention.
   */
  fromAgent: z.string().min(1),

  /**
   * Who must answer. Each entry is either a bare agent name (e.g.
   * "Scrooge", "Helena") or the literal string "CEO" for Marc.
   * Multiple entries = any one of them can respond.
   */
  requestedOf: z.array(z.string().min(1)).min(1),

  /** The decision question the agent cannot resolve within its mandate. */
  question: z.string().min(1),

  /**
   * Supporting context so the respondent has enough information to
   * answer without reading the agent's internal state.
   */
  context: z.string().min(1),

  /**
   * Enumerated options the respondent may choose from.
   * Empty array = free-form answer accepted.
   */
  options: z.array(z.string()),

  /**
   * ISO 8601 timestamp by which the decision is needed.
   * Omit when there is no hard deadline.
   */
  deadline: z.string().optional(),

  /**
   * ISO 8601 timestamp when the request was raised (usually equals the
   * event's `as_of`; provided explicitly for correlation).
   */
  raisedAt: z.string().min(1),
});

export type AgentDecisionRequiredPayload = z.infer<typeof agentDecisionRequiredPayloadSchema>;

export function makeAgentDecisionRequired(args: {
  asOf: string;
  entity: string;
  actor: Actor;
  citations: string[];
  payload: AgentDecisionRequiredPayload;
  eventId?: string;
}): Event {
  return eventSchema.parse({
    event_id: args.eventId ?? newEventId(),
    type: "AgentDecisionRequired",
    as_of: args.asOf,
    entity: args.entity,
    actor: args.actor,
    citations: args.citations,
    payload: agentDecisionRequiredPayloadSchema.parse(args.payload),
  });
}
